#!/usr/bin/env python3
"""Extract cookies from browser and save as Netscape format for yt-dlp."""

import sys
import os
try:
    import browser_cookie3
except ImportError:
    print("Error: Install browser-cookie3 first: pip3 install browser-cookie3")
    sys.exit(1)

def export_cookies(domain=None, browser='chrome', output_file='cookies.txt'):
    """Export cookies from browser to Netscape format."""
    
    browsers = {
        'chrome': browser_cookie3.chrome,
        'chromium': browser_cookie3.chromium,
        'firefox': browser_cookie3.firefox,
        'edge': browser_cookie3.edge,
    }
    
    if browser not in browsers:
        print(f"Browser {browser} not supported. Try: chrome, chromium, firefox, edge")
        return False
    
    try:
        cookiejar = browsers[browser](domain_name=domain)
    except Exception as e:
        print(f"Error accessing browser cookies: {e}")
        return False
    
    with open(output_file, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write(f"# Generated by export_cookies.py\n")
        f.write(f"# domain={domain or 'all'}\n")
        f.write(f"# browser={browser}\n\n")
        
        for cookie in cookiejar:
            # Format: domain, flag, path, secure, expiration, name, value
            domain = cookie.domain
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie.path or '/'
            secure = 'TRUE' if cookie.secure else 'FALSE'
            expires = int(cookie.expires) if cookie.expires else 0
            name = cookie.name
            value = cookie.value
            
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
    
    print(f"Exported {len(cookiejar)} cookies to {output_file}")
    return True

if __name__ == '__main__':
    domain = sys.argv[1] if len(sys.argv) > 1 else None
    browser = sys.argv[2] if len(sys.argv) > 2 else 'chrome'
    output = sys.argv[3] if len(sys.argv) > 3 else 'cookies.txt'
    
    if export_cookies(domain, browser, output):
        print(f"Run: yt-dlp --cookies {output} <url>")
    else:
        print("Cookie export failed")
        sys.exit(1)
