#!/bin/bash
# Extract cookies from browser for yt-dlp
# Usage: ./get_cookies.sh <domain> > cookies.txt

DOMAIN=${1:-example.com}
BROWSER=${2:-chrome}

echo "# Netscape HTTP Cookie File"
echo "# Generated by get_cookies.sh"
echo "# domain=$DOMAIN"
echo ""

# Try different browser cookie locations
COOKIE_PATHS=(
    "$HOME/.config/google-chrome/Default/Cookies"
    "$HOME/.config/chromium/Default/Cookies"
    "$HOME/.mozilla/firefox/*.default/cookies.sqlite"
)

for path in "${COOKIE_PATHS[@]}"; do
    if [ -e "$path" ]; then
        echo "Found cookies at: $path"
        echo "Use browser_cookie3 in Python or export manually"
        break
    fi
done

echo ""
echo "Alternative: Install cookies.txt extension in browser,"
echo "navigate to site, export cookies, and save as cookies.txt"
